### ISSUE TITLE
Translate it to chinese , is it permitted？

### ISSUE THREAD

**Issue by sgzqc** [diegoinacio/computer-vision-notebooks#10]
Hi diegoinacio,
       I am a  new computer vision learner ,  your work is so amazing that makes me understanding the concept easily.
      So I will be appreciated if you allow me to  translate the article into Chinese in my blog.
      I  am looking forward to your reply.
      Best wishes to you!

**Comment by diegoinacio** [comment]
Hi sgzqc,
Hope you are doing well. 
I'm very glad to know that this repository is helping you in some way.
And answering you question.. yes sure! Feel free to translate the articles in your blog.
If any doubt arises during this process, please do not hesitate to get in touch. I'll do my best to try and help you.
All the best!
